# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build and test

on:
  push:
  pull_request:

env:
  GOAMD64: v2

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.19' ]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
        cache: true

    - name: Install dependencies
      run: |
        go mod download
        go install github.com/sweoggy/slow-test-blocker/src

    - name: Test
      run: go test -v ./...

    - name: Create a Release
      id: release_step
      if: github.ref == 'refs/heads/main'
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ secrets.ACCESS_TOKEN }}
        automatic_release_tag: latest
        title: ${{ github.sha }}

  release:
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.19' ]
        goos: [linux, windows]
        goarch: [amd64, arm64]

    steps:
      - uses: actions/checkout@v3

      - name: Release
        if: github.ref == 'refs/heads/main'
        uses: wangyoucao577/go-release-action@v1.32
        with:
          project_path: ./src
          github_token: ${{ secrets.ACCESS_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          release_tag: latest
          extra_files: LICENSE README.md